CREATE DATABASE IF NOT EXISTS roles_db;
CREATE DATABASE IF NOT EXISTS permissions_db;

GRANT ALL PRIVILEGES ON roles_db.* TO '${DB_USER}'@'%';
GRANT ALL PRIVILEGES ON permissions_db.* TO '${DB_USER}'@'%';
FLUSH PRIVILEGES;